pages: 
    stage: deploy
    script:
    - mkdir .public
    - cp -r * .public
    - mkdir public
    - ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
    - cd .public
    - ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'

    artifacts:
        paths:
        - public
    only:
    - main