pages: 
    stage: deploy
    script:
    - mkdir .public
    - rsync -r * .public
    - mkdir public
    - mv .public public
    - ls .
    - ls ./public
    artifacts:
        paths:
        - public
    only:
    - main